site_name: Documentacion de la tarea de cuadratura Gaussiana

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  palette: 
    scheme: default
    primary: deep purple
    accent: deep purple

plugins:
  - mkdocstrings

nav:
- Home: index.md
- Explicacion: explanation.md
- Tutorial: tutorials.md
- Referencia: reference.md 
