site_name: Documentacion de la tarea de cuadratura Gaussiana

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
 extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js
theme:
  name: material
  palette: 
    scheme: default
    primary: deep purple
    accent: deep purple
plugins:
  - mkdocstrings 
nav:
- Home: index.md
- Explicacion: explanation.md
- Tutorial: tutorials.md
- Referencia: reference.md 
